In [2]:
import pandas as pd
from pathlib import Path

raw_path = Path("../data/raw")

files = [
    "01_fund_master.csv",
    "02_nav_history.csv",
    "07_scheme_performance.csv",
    "08_investor_transactions.csv"
]

for file in files:
    
    print(file)

    df = pd.read_csv(raw_path / file)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nShape:")
    print(df.shape)

    print("\nFirst 5 rows:")
    print(df.head())

01_fund_master.csv

Columns:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

Shape:
(40, 15)

First 5 rows:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02
02_nav_history.csv

Columns:
['amfi_code', 'date', 'nav']

Shape:
(46000, 3)

First 5 rows:
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692
07_scheme_performance.csv

Columns:
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

Shape:
(40, 19)

First 5 rows:
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low
08_investor_transactions.csv

Columns:
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

Shape:
(32778, 13)

First 5 rows:
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

In [3]:
df = pd.read_csv("../data/raw/01_fund_master.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None

In [5]:
df = pd.read_csv("../data/raw/01_fund_master.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None

In [9]:
df = pd.read_csv("../data/raw/07_scheme_performance.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB
None

In [10]:
df = pd.read_csv("../data/raw/08_investor_transactions.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB
None

In [11]:
df["transaction_type"].value_counts()

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [13]:
df["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [14]:
(df["amount_inr"] <= 0).sum()

np.int64(0)

In [15]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
print(df["transaction_date"].dtype)

datetime64[ns]

In [16]:
df.to_csv(
    "../data/processed/08_investor_transactions_cleaned.csv",
    index=False
)

print("Investor transactions cleaned and saved")

Investor transactions cleaned and saved

In [17]:
import pandas as pd
df = pd.read_csv("../data/raw/02_nav_history.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
None

In [18]:
df = pd.read_csv("../data/raw/02_nav_history.csv")
print(df.date)

0        2022-01-03
1        2022-01-04
2        2022-01-05
3        2022-01-06
4        2022-01-07
            ...
45995    2026-05-25
45996    2026-05-26
45997    2026-05-27
45998    2026-05-28
45999    2026-05-29
Name: date, Length: 46000, dtype: object

In [20]:
df["date"] = pd.to_datetime(df["date"])

In [21]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB
None

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
(df["nav"] <= 0).sum()

np.int64(0)

In [25]:
df = df.sort_values(by = ["amfi_code", "date"])

In [26]:
df.head(10)

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639
5755     100016 2022-01-10  510.7136
5756     100016 2022-01-11  513.5542
5757     100016 2022-01-12  512.3195
5758     100016 2022-01-13  510.2445
5759     100016 2022-01-14  514.3636

In [29]:
df["nav"].isnull().sum()

np.int64(0)

In [30]:
df.to_csv(
    "../data/processed/02_nav_history_cleaned.csv",
    index=False
)

print("NAV history cleaned and saved")

NAV history cleaned and saved

In [31]:
df = pd.read_csv("../data/raw/07_scheme_performance.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB
None

In [32]:
print(df.columns.tolist())

['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [33]:
df["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [34]:
df[
    [
        "return_1yr_pct",
        "return_3yr_pct",
        "return_5yr_pct"
    ]
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [35]:
df["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [36]:
df.to_csv(
    "../data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

In [38]:
df = pd.read_csv("../data/raw/01_fund_master.csv")
print(df)

    amfi_code                fund_house  \
0      119551           SBI Mutual Fund
1      119552           SBI Mutual Fund
2      119598           SBI Mutual Fund
3      119599           SBI Mutual Fund
4      119120           SBI Mutual Fund
5      100016          HDFC Mutual Fund
6      125497          HDFC Mutual Fund
7      100033          HDFC Mutual Fund
8      125498          HDFC Mutual Fund
9      100025          HDFC Mutual Fund
10     120503       ICICI Prudential MF
11     120504       ICICI Prudential MF
12     120505       ICICI Prudential MF
13     120506       ICICI Prudential MF
14     120507       ICICI Prudential MF
15     118632           Nippon India MF
16     118633           Nippon India MF
17     118634           Nippon India MF
18     118635           Nippon India MF
19     118636           Nippon India MF
20     120841         Kotak Mahindra MF
21     120842         Kotak Mahindra MF
22     120843         Kotak Mahindra MF
23     120844         Kotak Mahindra MF
24     119092          Axis Mutual Fund
25     119093          Axis Mutual Fund
26     119094          Axis Mutual Fund
27     119095          Axis Mutual Fund
28     101206  Aditya Birla Sun Life MF
29     101207  Aditya Birla Sun Life MF
30     101208  Aditya Birla Sun Life MF
31     102885           UTI Mutual Fund
32     102886           UTI Mutual Fund
33     102887           UTI Mutual Fund
34     148567            Mirae Asset MF
35     148568            Mirae Asset MF
36     148569            Mirae Asset MF
37     149322           DSP Mutual Fund
38     149323           DSP Mutual Fund
39     149324           DSP Mutual Fund

                                          scheme_name category  \
0           SBI Bluechip Fund - Regular Plan - Growth   Equity
1            SBI Bluechip Fund - Direct Plan - Growth   Equity
2          SBI Small Cap Fund - Regular Plan - Growth   Equity
3           SBI Small Cap Fund - Direct Plan - Growth   Equity
4        SBI Magnum Gilt Fund - Regular Plan - Growth     Debt
5           HDFC Top 100 Fund - Regular Plan - Growth   Equity
6            HDFC Top 100 Fund - Direct Plan - Growth   Equity
7   HDFC Mid-Cap Opportunities Fund - Regular - Gr...   Equity
8   HDFC Mid-Cap Opportunities Fund - Direct - Growth   Equity
9        HDFC Short Term Debt Fund - Regular - Growth     Debt
10         ICICI Pru Bluechip Fund - Regular - Growth   Equity
11          ICICI Pru Bluechip Fund - Direct - Growth   Equity
12           ICICI Pru Midcap Fund - Regular - Growth   Equity
13  ICICI Pru Value Discovery Fund - Regular - Growth   Equity
14           ICICI Pru Liquid Fund - Regular - Growth     Debt
15     Nippon India Large Cap Fund - Regular - Growth   Equity
16      Nippon India Large Cap Fund - Direct - Growth   Equity
17     Nippon India Small Cap Fund - Regular - Growth   Equity
18                     Nippon India ETF Nifty 50 BeES   Equity
19  Nippon India Gilt Securities Fund - Regular - ...     Debt
20             Kotak Bluechip Fund - Regular - Growth   Equity
21      Kotak Emerging Equity Fund - Regular - Growth   Equity
22             Kotak Flexicap Fund - Regular - Growth   Equity
23               Kotak Liquid Fund - Regular - Growth     Debt
24              Axis Bluechip Fund - Regular - Growth   Equity
25               Axis Bluechip Fund - Direct - Growth   Equity
26                Axis Midcap Fund - Regular - Growth   Equity
27             Axis Small Cap Fund - Regular - Growth   Equity
28      ABSL Frontline Equity Fund - Regular - Growth   Equity
29             ABSL Small Cap Fund - Regular - Growth   Equity
30                ABSL Liquid Fund - Regular - Growth     Debt
31         UTI Nifty 50 Index Fund - Regular - Growth   Equity
32                UTI Mid Cap Fund - Regular - Growth   Equity
33              UTI Flexi Cap Fund - Regular - Growth   Equity
34      Mirae Asset Large Cap Fund - Regular - Growth   Equity
35  Mirae Asset Emerging Bluechip Fund - Regular -...   Equity
36      Mirae Asset Tax Saver Fund - Regular - Growth   Equity
37         DSP Top 100 Equity Fund - Regular - Growth   Equity
38                 DSP Midcap Fund - Regular - Growth   Equity
39              DSP Small Cap Fund - Regular - Growth   Equity

       sub_category     plan launch_date                     benchmark  \
0         Large Cap  Regular  2006-02-14                 NIFTY 100 TRI
1         Large Cap   Direct  2013-01-01                 NIFTY 100 TRI
2         Small Cap  Regular  2009-09-09          BSE 250 SmallCap TRI
3         Small Cap   Direct  2013-01-01          BSE 250 SmallCap TRI
4              Gilt  Regular  2000-12-30     CRISIL Dynamic Gilt Index
5         Large Cap  Regular  1996-09-11                 NIFTY 100 TRI
6         Large Cap   Direct  2013-01-01                 NIFTY 100 TRI
7           Mid Cap  Regular  2007-06-25          NIFTY Midcap 150 TRI
8           Mid Cap   Direct  2013-01-01          NIFTY Midcap 150 TRI
9    Short Duration  Regular  2002-06-25  CRISIL Short Term Bond Index
10        Large Cap  Regular  2008-05-23                 NIFTY 100 TRI
11        Large Cap   Direct  2013-01-01                 NIFTY 100 TRI
12          Mid Cap  Regular  2004-10-28          NIFTY Midcap 150 TRI
13            Value  Regular  2004-08-16                 NIFTY 500 TRI
14           Liquid  Regular  2001-11-17   CRISIL Liquid Fund AI Index
15        Large Cap  Regular  2004-08-08                 NIFTY 100 TRI
16        Large Cap   Direct  2013-01-01                 NIFTY 100 TRI
17        Small Cap  Regular  2010-09-16          BSE 250 SmallCap TRI
18        Index/ETF   Direct  2001-12-28                  NIFTY 50 TRI
19             Gilt  Regular  1999-08-19     CRISIL Dynamic Gilt Index
20        Large Cap  Regular  2005-12-29                 NIFTY 100 TRI
21          Mid Cap  Regular  2007-03-30          NIFTY Midcap 150 TRI
22        Flexi Cap  Regular  2009-08-11                 NIFTY 500 TRI
23           Liquid  Regular  2004-03-03   CRISIL Liquid Fund AI Index
24        Large Cap  Regular  2010-01-05                 NIFTY 100 TRI
25        Large Cap   Direct  2013-01-01                 NIFTY 100 TRI
26          Mid Cap  Regular  2011-02-18           NIFTY Midcap 50 TRI
27        Small Cap  Regular  2013-11-29          BSE 250 SmallCap TRI
28        Large Cap  Regular  2002-08-30                 NIFTY 100 TRI
29        Small Cap  Regular  2007-05-31          BSE 250 SmallCap TRI
30           Liquid  Regular  2000-04-17   CRISIL Liquid Fund AI Index
31            Index  Regular  2000-03-06                  NIFTY 50 TRI
32          Mid Cap  Regular  2004-04-07          NIFTY Midcap 150 TRI
33        Flexi Cap  Regular  2005-05-18                 NIFTY 500 TRI
34        Large Cap  Regular  2008-04-04                 NIFTY 100 TRI
35  Large & Mid Cap  Regular  2010-07-09    NIFTY Large Midcap 250 TRI
36             ELSS  Regular  2015-12-28                 NIFTY 500 TRI
37        Large Cap  Regular  2003-03-10                 NIFTY 100 TRI
38          Mid Cap  Regular  2006-11-16          NIFTY Midcap 150 TRI
39        Small Cap  Regular  2007-06-14          BSE 250 SmallCap TRI

    expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0                1.54            1.0             500                1000
1                0.66            1.0             500                1000
2                1.43            1.0             500                1000
3                0.72            1.0             500                1000
4                0.77            0.0             500                1000
5                1.55            1.0             500                1000
6                0.92            1.0             500                1000
7                1.38            1.0             500                1000
8                0.78            1.0             500                1000
9                0.56            0.5             500                1000
10               1.42            1.0             500                1000
11               0.80            1.0             500                1000
12               1.36            1.0             500                1000
13               1.41            1.0             500                1000
14               0.74            0.0             500                5000
15               1.51            1.0             500                1000
16               0.72            1.0             500                1000
17               1.53            1.0             500                1000
18               0.89            0.0             500                 100
19               0.55            0.0             500                1000
20               1.59            1.0             500                1000
21               1.56            1.0             500                1000
22               1.45            1.0             500                1000
23               0.60            0.0             500                5000
24               1.64            1.0             500                1000
25               0.75            1.0             500                1000
26               1.38            1.0             500                1000
27               1.38            1.0             500                1000
28               1.60            1.0             500                1000
29               1.53            1.0             500                1000
30               0.79            0.0             500                5000
31               1.57            0.0             500                1000
32               1.51            1.0             500                1000
33               1.64            1.0             500                1000
34               1.46            1.0             500                1000
35               1.52            1.0             500                1000
36               1.60            1.0             500                1000
37               1.54            1.0             500                1000
38               1.61            1.0             500                1000
39               1.52            1.0             500                1000

           fund_manager    risk_category sebi_category_code
0         Sohini Andani         Moderate               EC01
1         Sohini Andani         Moderate               EC01
2         R. Srinivasan        Very High               EC03
3         R. Srinivasan        Very High               EC03
4          Dinesh Ahuja              Low               DC02
5          Rahul Baijal         Moderate               EC01
6          Rahul Baijal         Moderate               EC01
7       Chirag Setalvad             High               EC02
8       Chirag Setalvad             High               EC02
9          Anil Bamboli              Low               DC02
10       Anish Tawakley         Moderate               EC01
11       Anish Tawakley         Moderate               EC01
12       Sankaran Naren             High               EC02
13       Sankaran Naren  Moderately High               EC06
14        Rahul Goswami              Low               DC01
15     Sailesh Raj Bhan         Moderate               EC01
16     Sailesh Raj Bhan         Moderate               EC01
17          Samir Rachh        Very High               EC03
18          Vishal Jain         Moderate               EI01
19         Vivek Sharma              Low               DC02
20     Harsha Upadhyaya         Moderate               EC01
21      Pankaj Tibrewal             High               EC02
22      Pankaj Tibrewal  Moderately High               EC04
23       Deepak Agrawal              Low               DC01
24    Shreyash Devalkar         Moderate               EC01
25    Shreyash Devalkar         Moderate               EC01
26        Jinesh Gopani             High               EC02
27        Anupam Tiwari        Very High               EC03
28         Mahesh Patil         Moderate               EC01
29       Mircea Ciobanu        Very High               EC03
30        Maneesh Dangi              Low               DC01
31  Sharwan Kumar Goyal         Moderate               EI01
32           V Srivatsa             High               EC02
33           Ajay Tyagi  Moderately High               EC04
34         Gaurav Misra         Moderate               EC01
35       Neelesh Surana  Moderately High               EC04
36       Neelesh Surana             High               EC05
37         Apoorva Shah         Moderate               EC01
38         Vinit Sambre             High               EC02
39         Vinit Sambre        Very High               EC03

In [41]:
print(df.columns.tolist())

['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

In [42]:
for col in df.columns:
    print(col)

amfi_code
fund_house
scheme_name
category
sub_category
plan
launch_date
benchmark
expense_ratio_pct
exit_load_pct
min_sip_amount
min_lumpsum_amount
fund_manager
risk_category
sebi_category_code

In [43]:
df.to_csv(
    "../data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

In [44]:
import pandas as pd
from pathlib import Path

raw_path = Path("../data/raw")
processed_path = Path("../data/processed")

files = [
    "01_fund_master.csv",
    "03_aum_by_fund_house.csv",
    "04_monthly_sip_inflows.csv",
    "05_category_inflows.csv",
    "06_industry_folio_count.csv",
    "09_portfolio_holdings.csv",
    "10_benchmark_indices.csv"
]

for file in files:
    print(f"\nProcessing {file}")

    df = pd.read_csv(raw_path / file)
    print("Shape:", df.shape)
    print("Missing Values:")
    print(df.isnull().sum().sum())

    cleaned_name = file.replace(".csv", "_cleaned.csv")
    df.to_csv(processed_path / cleaned_name, index=False)

    print(f"Saved: {cleaned_name}")

print("\nAll remaining datasets processed successfully!")

Processing 01_fund_master.csv
Shape: (40, 15)
Missing Values:
0
Saved: 01_fund_master_cleaned.csv

Processing 03_aum_by_fund_house.csv
Shape: (90, 5)
Missing Values:
0
Saved: 03_aum_by_fund_house_cleaned.csv

Processing 04_monthly_sip_inflows.csv
Shape: (48, 6)
Missing Values:
12
Saved: 04_monthly_sip_inflows_cleaned.csv

Processing 05_category_inflows.csv
Shape: (144, 3)
Missing Values:
0
Saved: 05_category_inflows_cleaned.csv

Processing 06_industry_folio_count.csv
Shape: (21, 6)
Missing Values:
0
Saved: 06_industry_folio_count_cleaned.csv

Processing 09_portfolio_holdings.csv
Shape: (322, 8)
Missing Values:
0
Saved: 09_portfolio_holdings_cleaned.csv

Processing 10_benchmark_indices.csv
Shape: (8050, 3)
Missing Values:
0
Saved: 10_benchmark_indices_cleaned.csv

All remaining datasets processed successfully!